global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'extremenotes_backend'
    static_configs:
      - targets: ['backend:4000']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
